In [3]:
import pandas as pd

## read data from excel files :

In [4]:
# --> In a excel workbook where multiple sheet are there only the first one is loaded.

In [5]:

pd.read_excel(r"C:\Users\ANUBHAV\Downloads\Banking_Dashboard_Random_Dataset.xlsx")

,CustomerID,CustomerName,Email,City,State,JoinDate
0,C001,Customer 1,customer1@mail.com,Los Angeles,CA,2023-06-10
1,C002,Customer 2,customer2@mail.com,Chicago,IL,2024-04-11
2,C003,Customer 3,customer3@mail.com,Chicago,IL,2023-02-14
3,C004,Customer 4,customer4@mail.com,New York,NY,2024-08-03
4,C005,Customer 5,customer5@mail.com,Houston,TX,2023-06-16
...,...,...,...,...,...,...
95,C096,Customer 96,customer96@mail.com,New York,NY,2024-10-15
96,C097,Customer 97,customer97@mail.com,Houston,TX,2023-03-07
97,C098,Customer 98,customer98@mail.com,Chicago,IL,2025-01-23
98,C099,Customer 99,customer99@mail.com,Los Angeles,CA,2023-11-04
99,C100,Customer 100,customer100@mail.com,Los Angeles,CA,2025-06-12

In [6]:
# --> for other sheet we have to give the sheet_name in sheet_name parameter :

In [7]:
pd.read_excel(r"C:\Users\ANUBHAV\Downloads\Banking_Dashboard_Random_Dataset.xlsx" , sheet_name = 'Accounts')

   AccountID CustomerID AccountType   Balance
0       A001       C001      Salary   3297.70
1       A002       C002     Savings  11779.25
2       A003       C003     Current  21836.47
3       A004       C004     Current  16965.96
4       A005       C005      Salary  37629.23
..       ...        ...         ...       ...
95      A096       C096     Current  18885.47
96      A097       C097     Current  24901.87
97      A098       C098      Salary  47730.48
98      A099       C099      Salary  14636.75
99      A100       C100     Current  38919.06

[100 rows x 4 columns]

## Reading Text files :

In [12]:
# --> jiss text file ke data ko tabular form mai tab se seperate kiya gya ho usse read_csv ke through import krr skte hai.

In [10]:
# pd.read_csv(r'question_answer_pairs.txt' , sep = '\t')

## Importing json [ when data is stored locally ] :

In [9]:
pd.read_json(r"C:\Users\ANUBHAV\Data_Analytics\DAP\Data_Gathering\Datasets\train.json")

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

## Importing json [ when data is on the browser inside an link ] :

In [16]:
# pd.read_json(r" URL ")

In [18]:
import requests

url = "https://cdn.jsdelivr.net/npm/@fawazahmed0/currency-api@latest/v1/currencies.json"
data = requests.get(url).json()
data

{'1inch': '1inch',
 'aave': 'Aave',
 'ada': 'Cardano',
 'aed': 'Emirati Dirham',
 'afn': 'Afghan Afghani',
 'akt': 'Akash Network',
 'algo': 'Algorand',
 'all': 'Albanian Lek',
 'amd': 'Armenian Dram',
 'amp': 'Amp',
 'ang': 'Dutch Guilder',
 'aoa': 'Angolan Kwanza',
 'ape': 'ApeCoin',
 'apt': 'Aptos',
 'ar': 'Arweave',
 'arb': 'Arbitrum',
 'ars': 'Argentine Peso',
 'atom': 'Cosmos',
 'ats': 'Austrian Schilling',
 'aud': 'Australian Dollar',
 'avax': 'Avalanche',
 'awg': 'Aruban or Dutch Guilder',
 'axs': 'Axie Infinity',
 'azm': 'Azerbaijani Manat',
 'azn': 'Azerbaijan Manat',
 'bake': 'BakeryToken',
 'bam': 'Bosnian Convertible Mark',
 'bat': 'Basic Attention Token',
 'bbd': 'Barbadian or Bajan Dollar',
 'bch': 'Bitcoin Cash',
 'bdt': 'Bangladeshi Taka',
 'bef': 'Belgian Franc',
 'bgn': 'Bulgarian Lev',
 'bhd': 'Bahraini Dinar',
 'bif': 'Burundian Franc',
 'bmd': 'Bermudian Dollar',
 'bnb': 'Binance Coin',
 'bnd': 'Bruneian Dollar',
 'bob': 'Bolivian Bolíviano',
 'brl': 'Brazilian Real',
 'bsd': 'Bahamian Dollar',
 'bsv': 'Bitcoin SV',
 'bsw': 'Biswap',
 'btc': 'Bitcoin',
 'btcb': 'Bitcoin BEP2',
 'btg': 'Bitcoin Gold',
 'btn': 'Bhutanese Ngultrum',
 'btt': 'BitTorrent',
 'busd': 'Binance USD',
 'bwp': 'Botswana Pula',
 'byn': 'Belarusian Ruble',
 'byr': 'Belarusian Ruble',
 'bzd': 'Belizean Dollar',
 'cad': 'Canadian Dollar',
 'cake': 'PancakeSwap',
 'cdf': 'Congolese Franc',
 'celo': 'Celo',
 'cfx': 'Conflux',
 'chf': 'Swiss Franc',
 'chz': 'Chiliz',
 'clp': 'Chilean Peso',
 'cnh': 'Chinese Yuan Renminbi Offshore',
 'cny': 'Chinese Yuan Renminbi',
 'comp': 'Compound',
 'cop': 'Colombian Peso',
 'crc': 'Costa Rican Colon',
 'cro': 'Crypto.com Chain',
 'crv': 'Curve DAO Token',
 'cspr': 'Casper',
 'cuc': 'Cuban Convertible Peso',
 'cup': 'Cuban Peso',
 'cve': 'Cape Verdean Escudo',
 'cvx': 'Convex Finance',
 'cyp': 'Cypriot Pound',
 'czk': 'Czech Koruna',
 'dai': 'DAI',
 'dash': 'Digital Cash',
 'dcr': 'Decred',
 'dem': 'German Deutsche Mark',
 'dfi': 'DfiStarter',
 'djf': 'Djiboutian Franc',
 'dkk': 'Danish Krone',
 'doge': 'Dogecoin',
 'dop': 'Dominican Peso',
 'dot': 'Polkadot',
 'dydx': 'dYdX',
 'dzd': 'Algerian Dinar',
 'eek': 'Estonian Kroon',
 'egld': 'Elrond',
 'egp': 'Egyptian Pound',
 'enj': 'Enjin Coin',
 'eos': 'EOS',
 'ern': 'Eritrean Nakfa',
 'esp': 'Spanish Peseta',
 'etb': 'Ethiopian Birr',
 'etc': 'Ethereum Classic',
 'eth': 'Ethereum',
 'eur': 'Euro',
 'eurc': '',
 'fei': 'Fei USD',
 'fil': 'Filecoin',
 'fim': 'Finnish Markka',
 'fjd': 'Fijian Dollar',
 'fkp': 'Falkland Island Pound',
 'flow': 'Flow',
 'flr': 'FLARE',
 'frax': 'Frax',
 'frf': 'French Franc',
 'ftt': 'FarmaTrust',
 'gala': 'Gala',
 'gbp': 'British Pound',
 'gel': 'Georgian Lari',
 'ggp': 'Guernsey Pound',
 'ghc': 'Ghanaian Cedi',
 'ghs': 'Ghanaian Cedi',
 'gip': 'Gibraltar Pound',
 'gmd': 'Gambian Dalasi',
 'gmx': 'Goldmaxcoin',
 'gnf': 'Guinean Franc',
 'gno': 'Gnosis',
 'grd': 'Greek Drachma',
 'grt': 'The Graph',
 'gt': 'GateToken',
 'gtq': 'Guatemalan Quetzal',
 'gusd': 'Gemini US Dollar',
 'gyd': 'Guyanese Dollar',
 'hbar': 'Hedera',
 'hkd': 'Hong Kong Dollar',
 'hnl': 'Honduran Lempira',
 'hnt': 'Helium',
 'hot': 'Hydro Protocol',
 'hrk': 'Croatian Kuna',
 'ht': 'Huobi Token',
 'htg': 'Haitian Gourde',
 'huf': 'Hungarian Forint',
 'icp': 'Internet Computer',
 'idr': 'Indonesian Rupiah',
 'iep': 'Irish Pound',
 'ils': 'Israeli Shekel',
 'imp': 'Isle of Man Pound',
 'imx': 'Immutable X',
 'inj': 'Injective',
 'inr': 'Indian Rupee',
 'iqd': 'Iraqi Dinar',
 'irr': 'Iranian Rial',
 'isk': 'Icelandic Krona',
 'itl': 'Italian Lira',
 'jep': 'Jersey Pound',
 'jmd': 'Jamaican Dollar',
 'jod': 'Jordanian Dinar',
 'jpy': 'Japanese Yen',
 'kas': '',
 'kava': 'Kava',
 'kcs': 'Kucoin',
 'kda': 'Kadena',
 'kes': 'Kenyan Shilling',
 'kgs': 'Kyrgyzstani Som',
 'khr': 'Cambodian Riel',
 'klay': 'Klaytn',
 'kmf': 'Comorian Franc',
 'knc': 'Kyber Network Crystals',
 'kpw': 'North Korean Won',
 'krw': 'South Korean Won',
 'ksm': 'Kusama',
 'kwd': 'Kuwaiti Dinar',
 'kyd': 'Caymanian Dollar',
 'kzt': 'Kazakhstani Tenge',
 'lak': 'Lao Kip',
 'lbp': 'Lebanese Pound',
 'ldo': 'Lido DAO Token',
 'leo': 'LEOcoin',
 'link': 'Chainlink',
 'lkr': 'Sri Lankan Rupee',
 'lrc': 'Loopring',
 'lrd': 'Liberian Dollar',
 'lsl': 'Basotho Loti',
 'ltc': 'Litecoin',
 'ltl': 'Lithuanian Litas',
 'luf': 'Luxembourg Franc',
 'luna': 'Terra',
 'lunc': '',
 'lvl': 'Latvian Lat',
 'lyd': 'Libyan Dinar',
 'mad': 'Moroccan Dirham',
 'mana': 'Mana Coin Decentraland',
 'mbx': 'MobieCoin',
 'mdl': 'Moldovan Leu',
 'mga': 'Malagasy Ariary',
 'mgf': 'Malagasy Franc',
 'mina': 'Mina',
 'mkd': 'Macedonian Denar',
 'mkr': 'Maker',
 'mmk': 'Burmese Kyat',
 'mnt': 'Mongolian Tughrik',
 'mop': 'Macau Pataca',
 'mro': 'Mauritanian Ouguiya',
 'mru': 'Mauritanian Ouguiya',
 'mtl': 'Maltese Lira',
 'mur': 'Mauritian Rupee',
 'mvr': 'Maldivian Rufiyaa',
 'mwk': 'Malawian Kwacha',
 'mxn': 'Mexican Peso',
 'mxv': '',
 'myr': 'Malaysian Ringgit',
 'mzm': 'Mozambican Metical',
 'mzn': 'Mozambican Metical',
 'nad': 'Namibian Dollar',
 'near': 'NEAR Protocol',
 'neo': 'NEO',
 'nexo': 'NEXO',
 'nft': 'NFT',
 'ngn': 'Nigerian Naira',
 'nio': 'Nicaraguan Cordoba',
 'nlg': 'Dutch Guilder',
 'nok': 'Norwegian Krone',
 'npr': 'Nepalese Rupee',
 'nzd': 'New Zealand Dollar',
 'okb': 'Okex',
 'omr': 'Omani Rial',
 'one': 'Menlo One',
 'op': 'Optimism',
 'ordi': '',
 'pab': 'Panamanian Balboa',
 'paxg': 'PAX Gold',
 'pen': 'Peruvian Sol',
 'pepe': '',
 'pgk': 'Papua New Guinean Kina',
 'php': 'Philippine Peso',
 'pi': 'Plian',
 'pkr': 'Pakistani Rupee',
 'pln': 'Polish Zloty',
 'pol': 'Proof Of Liquidity',
 'pte': 'Portuguese Escudo',
 'pyg': 'Paraguayan Guarani',
 'qar': 'Qatari Riyal',
 'qnt': 'Quant',
 'qtum': 'QTUM',
 'rol': 'Romanian Leu',
 'ron': 'Romanian Leu',
 'rpl': 'Rocket Pool',
 'rsd': 'Serbian Dinar',
 'rub': 'Russian Ruble',
 'rune': 'THORChain (ERC20)',
 'rvn': 'Ravencoin',
 'rwf': 'Rwandan Franc',
 'sand': 'The Sandbox',
 'sar': 'Saudi Arabian Riyal',
 'sbd': 'Solomon Islander Dollar',
 'scr': 'Seychellois Rupee',
 'sdd': 'Sudanese Dinar',
 'sdg': 'Sudanese Pound',
 'sek': 'Swedish Krona',
 'sgd': 'Singapore Dollar',
 'shib': 'Shiba Inu',
 'shp': 'Saint Helenian Pound',
 'sit': 'Slovenian Tolar',
 'skk': 'Slovak Koruna',
 'sle': 'Sierra Leonean Leone',
 'sll': 'Sierra Leonean Leone',
 'snx': 'Synthetix Network',
 'sol': 'Solana',
 'sos': 'Somali Shilling',
 'spl': 'Seborgan Luigino',
 'srd': 'Surinamese Dollar',
 'srg': 'Surinamese Guilder',
 'ssp': 'South Sudanese Pound',
 'std': 'Sao Tomean Dobra',
 'stn': 'Sao Tomean Dobra',
 'stx': 'Stacks',
 'sui': 'Sui',
 'svc': 'Salvadoran Colon',
 'syp': 'Syrian Pound',
 'szl': 'Swazi Lilangeni',
 'thb': 'Thai Baht',
 'theta': 'Theta',
 'tjs': 'Tajikistani Somoni',
 'tmm': 'Turkmenistani Manat',
 'tmt': 'Turkmenistani Manat',
 'tnd': 'Tunisian Dinar',
 'top': "Tongan Pa'anga",
 'trl': '',
 'trx': 'TRON',
 'try': 'Turkish Lira',
 'ttd': 'Trinidadian Dollar',
 'tusd': 'True USD',
 'tvd': 'Tuvaluan Dollar',
 'twd': 'Taiwan New Dollar',
 'twt': 'Trust Wallet Token',
 'tzs': 'Tanzanian Shilling',
 'uah': 'Ukrainian Hryvnia',
 'ugx': 'Ugandan Shilling',
 'uni': 'Uniswap',
 'usd': 'US Dollar',
 'usdc': 'USDC',
 'usdd': '',
 'usdp': 'USDP Stablecoin',
 'usdt': 'Tether',
 'uyu': 'Uruguayan Peso',
 'uzs': 'Uzbekistani Som',
 'val': 'Vatican City Lira',
 'veb': 'Venezuelan Bolívar',
 'ved': '',
 'vef': 'Venezuelan Bolívar',
 'ves': 'Venezuelan Bolívar',
 'vet': 'Vechain',
 'vnd': 'Vietnamese Dong',
 'vuv': 'Ni-Vanuatu Vatu',
 'waves': 'Waves',
 'wemix': 'WEMIX',
 'woo': 'WOO Network',
 'wst': 'Samoan Tala',
 'xaf': 'Central African CFA Franc BEAC',
 'xag': 'Silver Ounce',
 'xau': 'Gold Ounce',
 'xaut': 'Tether Gold',
 'xbt': '',
 'xcd': 'East Caribbean Dollar',
 'xcg': 'Xchange',
 'xch': 'Chia',
 'xdc': 'XDC Network',
 'xdr': 'IMF Special Drawing Rights',
 'xec': 'Eternal Coin',
 'xem': 'NEM',
 'xlm': 'Stellar Lumen',
 'xmr': 'Monero',
 'xof': 'CFA Franc',
 'xpd': 'Palladium Ounce',
 'xpf': 'CFP Franc',
 'xpt': 'Platinum Ounce',
 'xrp': 'Ripple',
 'xtz': 'Tezos',
 'yer': 'Yemeni Rial',
 'zar': 'South African Rand',
 'zec': 'ZCash',
 'zil': 'Zilliqa',
 'zmk': 'Zambian Kwacha',
 'zmw': 'Zambian Kwacha',
 'zwd': 'Zimbabwean Dollar',
 'zwg': '',
 'zwl': 'Zimbabwean Dollar'}

In [19]:
df = pd.DataFrame(data.items(), columns=["currency_code", "currency_name"])

df.head()

  currency_code   currency_name
0         1inch           1inch
1          aave            Aave
2           ada         Cardano
3           aed  Emirati Dirham
4           afn  Afghan Afghani

## Working with SQL :

In [10]:
!pip install mysql.connector

Collecting mysql.connector
  Downloading mysql-connector-2.2.9.tar.gz (11.9 MB)
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
      --------------------------------------- 0.3/11.9 MB ? eta -:--:--
     ------- -------------------------------- 2.4/11.9 MB 8.6 MB/s eta 0:00:02
     ----------------- ---------------------- 5.2/11.9 MB 11.4 MB/s eta 0:00:01
     ------------------------- -------------- 7.6/11.9 MB 11.0 MB/s eta 0:00:01
     ---------------------------------- ---- 10.5/11.9 MB 11.8 MB/s eta 0:00:01
     ---------------------------------------- 11.9/11.9 MB 11.4 MB/s  0:00:01
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: mysql.connector
  Building wheel for mysql.connector (pyproject.toml): started
  Building wheel for mysql.connector (pyproject.toml): finished with status 'done'
  Created wheel for mysql.connector: filename=mysql_connector-2.2.9-cp314-cp314-win_amd64.whl size=248716 sha256=8e66b5b1b9da3fa3ea9f7596acb9061b20f4fb6c6e09a9f8be5e24342e1e57a4
  Stored in directory: c:\users\anubhav\appdata\local\pip\cache\wheels\a2\5a\60\e03682d488f501428666827b000cfa0da00163afcd74ce2c14
Successfully built mysql.connector
Installing collected packages: mysql.connector
Successfully installed mysql.connector-2.2.9

[notice] A new release of pip is available: 26.1.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
# NOTE :  only example base ( actual implementation nahi hai )

In [21]:


import mysql.connector

In [22]:
Conn = mysql.connector.connect(host = 'localhost' , user = 'root' , password = '1020153257' , database = 'sales')

In [24]:
pd.read_sql_query("SELECT * FROM dim_customer" , Conn)

C:\Users\ANUBHAV\AppData\Local\Temp\ipykernel_6456\911743928.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT * FROM dim_customer" , Conn)

,customer_key,customer_id,first_name,last_name,gender,email,phone,country,state,city,join_date
0,1,CUST0001,Antonio,Kelly,M,richard16@example.net,9904005277,Tunisia,New Hampshire,Lake Timothy,2021-09-08
1,2,CUST0002,Todd,Lucas,F,danielsnyder@example.org,0012907800627,Djibouti,Wyoming,Nicholasstad,2023-08-05
2,3,CUST0003,Matthew,Lee,M,joseph40@example.net,001596505299143,Guinea-Bissau,Montana,Janiceton,2022-03-27
3,4,CUST0004,Gregory,Young,F,juan09@example.net,182656936555456,Tajikistan,Louisiana,Josephstad,2022-08-11
4,5,CUST0005,Nathan,Smith,F,wroberts@example.net,3807169186,Tokelau,Massachusetts,Bryantbury,2022-04-24
...,...,...,...,...,...,...,...,...,...,...,...
495,496,CUST0496,David,Downs,F,travissmith@example.org,999404911880275,Bulgaria,California,Kellyport,2023-07-15
496,497,CUST0497,Jessica,Williams,F,donald87@example.net,0012499424826,United Kingdom,Virginia,Allenport,2020-12-12
497,498,CUST0498,Beth,Watson,F,anthony03@example.net,982208134043096,Turkmenistan,Alaska,New Robertborough,2020-12-02
498,499,CUST0499,Christina,Caldwell,M,malikchan@example.com,50169724390470,Canada,Vermont,Davidfurt,2021-10-01
499,500,CUST0500,Dale,Smith,M,hansonaaron@example.org,164562510975115,Senegal,Virginia,Paulabury,2023-10-08