In [1]:
import pandas as pd

# read data from excel files : 
# --> in a excel workbook where multiple sheet are there only the first one is loaded.

In [2]:

pd.read_excel(r"C:\Users\ANUBHAV\Downloads\Banking_Dashboard_Random_Dataset.xlsx")

,CustomerID,CustomerName,Email,City,State,JoinDate
0,C001,Customer 1,customer1@mail.com,Los Angeles,CA,2023-06-10
1,C002,Customer 2,customer2@mail.com,Chicago,IL,2024-04-11
2,C003,Customer 3,customer3@mail.com,Chicago,IL,2023-02-14
3,C004,Customer 4,customer4@mail.com,New York,NY,2024-08-03
4,C005,Customer 5,customer5@mail.com,Houston,TX,2023-06-16
...,...,...,...,...,...,...
95,C096,Customer 96,customer96@mail.com,New York,NY,2024-10-15
96,C097,Customer 97,customer97@mail.com,Houston,TX,2023-03-07
97,C098,Customer 98,customer98@mail.com,Chicago,IL,2025-01-23
98,C099,Customer 99,customer99@mail.com,Los Angeles,CA,2023-11-04
99,C100,Customer 100,customer100@mail.com,Los Angeles,CA,2025-06-12

# --> for other sheet we have to give the sheet_name in sheet_name parameter :

In [8]:
pd.read_excel(r"C:\Users\ANUBHAV\Downloads\Banking_Dashboard_Random_Dataset.xlsx" , sheet_name = 'Accounts')

   AccountID CustomerID AccountType   Balance
0       A001       C001      Salary   3297.70
1       A002       C002     Savings  11779.25
2       A003       C003     Current  21836.47
3       A004       C004     Current  16965.96
4       A005       C005      Salary  37629.23
..       ...        ...         ...       ...
95      A096       C096     Current  18885.47
96      A097       C097     Current  24901.87
97      A098       C098      Salary  47730.48
98      A099       C099      Salary  14636.75
99      A100       C100     Current  38919.06

[100 rows x 4 columns]

# Reading Text files : 
# --> jiss text file ke data ko tabular form mai tab se seperate kiya gya ho usse read_csv ke through import krr skte hai.

In [ ]:
pd.read_csv(r'question_answer_pairs.txt' , sep = '\t')

# Importing json [ when data is stored locally ] :

In [9]:
pd.read_json(r"C:\Users\ANUBHAV\Data_Analytics\DAP\Data_Gathering\Datasets\train.json")

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

# Importing json [ when data is on the browser inside an link ] :

In [ ]:
pd.read_json(r" URL ")

# Working with SQL :

In [10]:
!pip install mysql.connector

Collecting mysql.connector
  Downloading mysql-connector-2.2.9.tar.gz (11.9 MB)
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
      --------------------------------------- 0.3/11.9 MB ? eta -:--:--
     ------- -------------------------------- 2.4/11.9 MB 8.6 MB/s eta 0:00:02
     ----------------- ---------------------- 5.2/11.9 MB 11.4 MB/s eta 0:00:01
     ------------------------- -------------- 7.6/11.9 MB 11.0 MB/s eta 0:00:01
     ---------------------------------- ---- 10.5/11.9 MB 11.8 MB/s eta 0:00:01
     ---------------------------------------- 11.9/11.9 MB 11.4 MB/s  0:00:01
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: mysql.connector
  Building wheel for mysql.connector (pyproject.toml): started
  Building wheel for mysql.connector (pyproject.toml): finished with status 'done'
  Created wheel for mysql.connector: filename=mysql_connector-2.2.9-cp314-cp314-win_amd64.whl size=248716 sha256=8e66b5b1b9da3fa3ea9f7596acb9061b20f4fb6c6e09a9f8be5e24342e1e57a4
  Stored in directory: c:\users\anubhav\appdata\local\pip\cache\wheels\a2\5a\60\e03682d488f501428666827b000cfa0da00163afcd74ce2c14
Successfully built mysql.connector
Installing collected packages: mysql.connector
Successfully installed mysql.connector-2.2.9

[notice] A new release of pip is available: 26.1.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

# NOTE :  only example base ( actual implementation nahi hai )

In [11]:


import mysql.connector

In [ ]:
Conn = mysql.connector.connect(host = 'localhost' , user = 'root' , password = '1020153257' , database = 'world')

In [ ]:
pd.read_sql_query("SELECT * FROM city" , Conn)