In [2]:
import pandas as pd
import numpy as np

In [3]:
patients = pd.read_csv(r"C:\Users\ANUBHAV\Data_Analytics\DAP\Data_Cleaning\Dataset\patients.csv")
treatments = pd.read_csv(r"C:\Users\ANUBHAV\Data_Analytics\DAP\Data_Cleaning\Dataset\treatments.csv")
adverse_reactions = pd.read_csv(r"C:\Users\ANUBHAV\Data_Analytics\DAP\Data_Cleaning\Dataset\adverse_reactions.csv")
treatments_cut = pd.read_csv(r"C:\Users\ANUBHAV\Data_Analytics\DAP\Data_Cleaning\Dataset\treatments_cut.csv")

In [4]:
# view datasets 

patients.head()

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
0,1,female,Zoe,Wellish,576 Brown Bear Drive,Rancho California,California,92390.0,United States,951-719-9170ZoeWellish@superrito.com,7/10/1976,121.7,66,19.6
1,2,female,Pamela,Hill,2370 University Hill Road,Armstrong,Illinois,61812.0,United States,PamelaSHill@cuvox.de+1 (217) 569-3204,4/3/1967,118.8,66,19.2
2,3,male,Jae,Debord,1493 Poling Farm Road,York,Nebraska,68467.0,United States,402-363-6804JaeMDebord@gustr.com,2/19/1980,177.8,71,24.8
3,4,male,Liêm,Phan,2335 Webster Street,Woodbridge,NJ,7095.0,United States,PhanBaLiem@jourrapide.com+1 (732) 636-8246,7/26/1951,220.9,70,31.7
4,5,male,Tim,Neudorf,1428 Turkey Pen Lane,Dothan,AL,36303.0,United States,334-515-7487TimNeudorf@cuvox.de,2/18/1928,192.3,27,26.1

In [5]:
treatments.head()

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
0,veronika,jindrová,41u - 48u,-,7.63,7.20,NaN
1,elliot,richardson,-,40u - 45u,7.56,7.09,0.97
2,yukitaka,takenaka,-,39u - 36u,7.68,7.25,NaN
3,skye,gormanston,33u - 36u,-,7.97,7.62,0.35
4,alissa,montez,-,33u - 29u,7.78,7.46,0.32

In [6]:
treatments_cut.head()

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
0,jožka,resanovič,22u - 30u,-,7.56,7.22,0.34
1,inunnguaq,heilmann,57u - 67u,-,7.85,7.45,NaN
2,alwin,svensson,36u - 39u,-,7.78,7.34,NaN
3,thể,lương,-,61u - 64u,7.64,7.22,0.92
4,amanda,ribeiro,36u - 44u,-,7.85,7.47,0.38

In [7]:
adverse_reactions.head()

  given_name     surname           adverse_reaction
0      berta  napolitani  injection site discomfort
1       lena        baer               hypoglycemia
2     joseph         day               hypoglycemia
3     flavia  fiorentino                      cough
4    manouck     wubbels          throat irritation

In [8]:
treatments.shape

(280, 7)

In [9]:
treatments_cut.shape

(70, 7)

# 1. Summary About the data : 

- This is a dataset about 500 patients of which 350 patients participated in a clinincal trial. None of the patients were using Novodra ( a popular 
injectable insulin ) or Auralin ( the oral insulin being researched ) as their primary source of insulin before. All were experiencing elevated HbA1c levels.
- All 350 patients were treated with Novodra to establish a baseline HbA1c level and insulin dose. After 4 weeks , which isn't enough time to capture all the change in HbA1c that can be attributed by the switch to Auralin or Novodra :

   --> 175 patients switched to Auralin for 24 weeks.
   
   --> 175 patients continued using Novodra for 24 weeks.

# 2. Write Column descriptions : 

- patient_id : the unique identifier for each patient in the Master Patient Index ( i.e. patient database ) of the pharmaceutical company that is
  producing Auralin.
- assigned_sex : the assigned sex of each patient at birth ( male or female ) .
- given_name : the given name ( i.e first name ) of each patient.
- surname : the surname ( i.e last name ) of each patient.
- address : the main address for each patient.
- city : the corrosponding city for the main address of each patient.
- state : the corrosponding state for the main address of each patient.
- zip_code : the corrosponding zip code for the main address of each patient.
- country : the corrosponding country for the main address of each patient ( all United states for this clinical trial ).
- contact : phone number and email information for each patient.
- birthdate : the date of birth of each patient ( month / day / year ). The inclusion criteria for this clinical trial is age >= 18 ( there is no
  maximum age because diabetes is a growing problem among the elderly population.
- weight : the weight of each patient in pounds (lbs).
- height : the height of each patient in inches (in).
- bmi : the Body Mass Index(BMI) of eachh patient. BMI is a simple calculation using a person's height and weight. The formula is BMI = kg/m2 where kg  is a person's weight in kilograms and m2 is their in metres squared. A BMI of 25.0 or more is overweight , while the healthy range is 18.5 to 24.9. The inclusion criteria for this clinical trial is 16 >= BMI >= 38.

# Table -> treatments and treatment_cut :

1. given_name: the given name of each patient in the Master Patient Index that took part in the clinical trial. 
2. surname: the surname of each patient in the Master Patient Index that took part in the clinical trial.
3. auralin: the baseline median daily dose of insulin from the week prior to switching to Auralin (the number before the dash) and the ending median daily dose of insulin at the end of the 24 weeks of treatment measured over the 24th week of treatment (the number after the dash). Both are measured in units (shortform 'u'), which is the international unit of measurement and the standard measurement for insulin.
4. novodra: same as above, except for patients that continued treatment with Novodra.
5. hba1c_start: the patient's HbA1c level at the beginning of the first week of treatment. HbA1c stands for Hemoglobin A1c. The HbA1c test measures what the average blood sugar has been over the past three months. It is thus a powerful way to get an overall sense of how well diabetes has been controlled. Everyone with diabetes should have this test 2 to 4 times per year. Measured in %.
6. hba1c_end: the patient's HbA1c level at the end of the last week of treatment.

7. hba1c_change: the change in the patient's HbA1c level from the start of treatment to the end, i.e., hba1c_start - hba1c_end. For Auralin to be deemed effective, it must be "noninferior" to Novodra, the current standard for insulin. This "noninferiority" is statistically defined as the upper bound of the 95% confidence interval being less than 0.4% for the difference between the mean HbA1c changes for Novodra and Auralin (i.e. Novodra minus Auralin).

# Table -> adverse_reactions : 

1. given_name: the given name of each patient in the Master Patient Index that took part in the clinical trial and had an adverse reaction (includes both patients treated Auralin and Novodra).

2. surname: the surname of each patient in the Master Patient Index that took part in the clinical trial and had an adverse reaction (includes both patients treated Auralin and Novodra).

3. adverse_reaction: the adverse reaction reported by the patient.

# 3. Add any additional information : 


-> Insulin resistance varies person to person, which is why both starting median daily dose and ending median daily dose are required, i.e., to calculate change in dose.

-> It is important to test drugs and medical products in the people they are meant to help. People of different age, race, sex, and ethnic group must be included in clinical trials. This diversity is reflected in the patients table.

# Types of Assessment :  

--> There are 2 types of assessment styles :-

    1. Manual :- Looking through the data manually in google sheets.
    2. Programatic :- By using pandas functions such as info(), describe() or sample()
    Steps in Assessment.
    
--> There are 2 steps involved in Assessment :-

    1. Discover
    2. Document

# 1. Manual Assessment  :

In [10]:
#--> Export data for manual assessment. 

with pd.ExcelWriter('clinical_trials.xlsx') as writer:
    patients.to_excel(writer , sheet_name = 'patients')
    treatments.to_excel(writer , sheet_name = 'treatments')
    treatments_cut.to_excel(writer , sheet_name = ' treatments_cut')
    adverse_reactions.to_excel(writer , sheet_name = 'adverse_reactions')

#--> Issues with the dataset : 


1. Dirty Data [ Quality Issues ] :

   :: Table -  `Patients`
   -  patient_id = 9 has misspelled name 'Dsvid' instead of 'David'.
   -  state column sometimes contain full name and some times abbriviations(short form).
   -  zip_code column has entries with 4 digits ( it must be 5 digits ).
   -  data missing for 12 patients in address , city , state , zip_code , country , contact.
   -  Incorrect datatype assigned to columns 'assigned_sex' , 'zip_code' , 'birthdate'.
   -  duplicate entries by the name of 'John Doe'.
   -  one paitient in the patients table has weight = 48 pound (impossible).
   -  one patient has height = 27 inches.
   -  birthdate column is in not in date format. 



   





   :: Table - `Treatments` &  `Treatments_cut`
    - the format of the columns 'given_name' and 'surname' is different from the same column in Patients table, As in patients table the both column         have their first characters as capital , but in the treatements table the column have all small characters.
    - remove 'u' from the Auralin and Novadra column.
    - '-' in Novadra and Auralin Column treated as NaN.
    -  missing values in hba1c_change column.
    -  one duplicated entry in the 'treatments' table  by the name Joseph day.
    -  the 'hba1c_change' has value 9 instead of 4. 
   









    :: Table - `Adverse_reaction`
    - given_name and surname are all in lower case.


















2. Messy Data [ Structural Issues ] :

   :: Table -  `Patients`
  - contact column contain both phone number and email. ( must be in seperated columns ).


    :: Table - `Treatments` &  `Treatments_cut`
    - Auralin and Novadra column should be split into 2 cols start and end dose.
   

    :: Table - `Adverse_reaction`
    - This table should not exist independently because this table only contain one unique column 'adverse_reaction' and it could be add in
       treatment table.

# 2. Programatic Assessment :

#--> Automatic Assessment : 
- head and tail
- sample
- info
- isnull
- duplicated
- describe

In [11]:
patients.head()

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
0,1,female,Zoe,Wellish,576 Brown Bear Drive,Rancho California,California,92390.0,United States,951-719-9170ZoeWellish@superrito.com,7/10/1976,121.7,66,19.6
1,2,female,Pamela,Hill,2370 University Hill Road,Armstrong,Illinois,61812.0,United States,PamelaSHill@cuvox.de+1 (217) 569-3204,4/3/1967,118.8,66,19.2
2,3,male,Jae,Debord,1493 Poling Farm Road,York,Nebraska,68467.0,United States,402-363-6804JaeMDebord@gustr.com,2/19/1980,177.8,71,24.8
3,4,male,Liêm,Phan,2335 Webster Street,Woodbridge,NJ,7095.0,United States,PhanBaLiem@jourrapide.com+1 (732) 636-8246,7/26/1951,220.9,70,31.7
4,5,male,Tim,Neudorf,1428 Turkey Pen Lane,Dothan,AL,36303.0,United States,334-515-7487TimNeudorf@cuvox.de,2/18/1928,192.3,27,26.1

In [13]:
patients.sample(5)  #--> repeat this 2-4 times to watch the random rows

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
18,19,male,William,Oates,441 Tibbs Avenue,Ekalaka,MT,59324.0,United States,406-775-2696WilliamVOates@armyspy.com,9/4/1949,202.2,64,34.7
296,297,female,Chỉ,Lâm,NaN,NaN,NaN,NaN,NaN,NaN,5/14/1990,181.1,63,32.1
319,320,female,Wilma,Olofsson,2235 Catherine Drive,Fargo,ND,58102.0,United States,701-235-3404WilmaOlofsson@teleworm.us,11/17/1985,154.9,69,22.9
463,464,female,Bouke,Glaser,3006 Maple Court,Owensville,MO,65066.0,United States,BoukeGlaser@einrot.com1 573 437 7334,10/21/1996,142.1,66,22.9
150,151,male,Felicijan,Bubanj,4556 Oakdale Avenue,Dundee,Florida,33838.0,United States,863-438-6922FelicijanBubanj@einrot.com,5/22/1957,226.6,71,31.6

In [14]:
patients.info()

<class 'pandas.DataFrame'>
RangeIndex: 503 entries, 0 to 502
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   patient_id    503 non-null    int64
 1   assigned_sex  503 non-null    str
 2   given_name    503 non-null    str
 3   surname       503 non-null    str
 4   address       491 non-null    str
 5   city          491 non-null    str
 6   state         491 non-null    str
 7   zip_code      491 non-null    float64
 8   country       491 non-null    str
 9   contact       491 non-null    str
 10  birthdate     503 non-null    str
 11  weight        503 non-null    float64
 12  height        503 non-null    int64
 13  bmi           503 non-null    float64
dtypes: float64(3), int64(2), str(9)
memory usage: 55.1 KB

In [16]:
patients[patients['address'].isnull()]

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
209,210,female,Lalita,Eldarkhanov,NaN,NaN,NaN,NaN,NaN,NaN,8/14/1950,143.4,62,26.2
219,220,male,Mỹ,Quynh,NaN,NaN,NaN,NaN,NaN,NaN,4/9/1978,237.8,69,35.1
230,231,female,Elisabeth,Knudsen,NaN,NaN,NaN,NaN,NaN,NaN,9/23/1976,165.9,63,29.4
234,235,female,Martina,Tománková,NaN,NaN,NaN,NaN,NaN,NaN,4/7/1936,199.5,65,33.2
242,243,male,John,O'Brian,NaN,NaN,NaN,NaN,NaN,NaN,2/25/1957,205.3,74,26.4
249,250,male,Benjamin,Mehler,NaN,NaN,NaN,NaN,NaN,NaN,10/30/1951,146.5,69,21.6
257,258,male,Jin,Kung,NaN,NaN,NaN,NaN,NaN,NaN,5/17/1995,231.7,69,34.2
264,265,female,Wafiyyah,Asfour,NaN,NaN,NaN,NaN,NaN,NaN,11/3/1989,158.6,63,28.1
269,270,female,Flavia,Fiorentino,NaN,NaN,NaN,NaN,NaN,NaN,10/9/1937,175.2,61,33.1
278,279,female,Generosa,Cabán,NaN,NaN,NaN,NaN,NaN,NaN,12/16/1962,124.3,69,18.4
286,287,male,Lewis,Webb,NaN,NaN,NaN,NaN,NaN,NaN,4/1/1979,155.3,68,23.6
296,297,female,Chỉ,Lâm,NaN,NaN,NaN,NaN,NaN,NaN,5/14/1990,181.1,63,32.1

In [17]:
treatments.info()

<class 'pandas.DataFrame'>
RangeIndex: 280 entries, 0 to 279
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   given_name    280 non-null    str
 1   surname       280 non-null    str
 2   auralin       280 non-null    str
 3   novodra       280 non-null    str
 4   hba1c_start   280 non-null    float64
 5   hba1c_end     280 non-null    float64
 6   hba1c_change  171 non-null    float64
dtypes: float64(3), str(4)
memory usage: 15.4 KB

In [18]:
treatments_cut.info()

<class 'pandas.DataFrame'>
RangeIndex: 70 entries, 0 to 69
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   given_name    70 non-null     str
 1   surname       70 non-null     str
 2   auralin       70 non-null     str
 3   novodra       70 non-null     str
 4   hba1c_start   70 non-null     float64
 5   hba1c_end     70 non-null     float64
 6   hba1c_change  42 non-null     float64
dtypes: float64(3), str(4)
memory usage: 4.0 KB

In [20]:
adverse_reactions.info()

<class 'pandas.DataFrame'>
RangeIndex: 34 entries, 0 to 33
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   given_name        34 non-null     str
 1   surname           34 non-null     str
 2   adverse_reaction  34 non-null     str
dtypes: str(3)
memory usage: 948.0 bytes

#--> finding duplicated data :

In [21]:


patients.duplicated().sum()

np.int64(0)

In [25]:
patients['patient_id'].duplicated().sum()

np.int64(0)

In [28]:


patients.duplicated(subset = ['given_name' , 'surname']).sum()

np.int64(5)

In [30]:

patients[patients.duplicated(subset = ['given_name' , 'surname'])]

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
229,230,male,John,Doe,123 Main Street,New York,NY,12345.0,United States,johndoe@email.com1234567890,1/1/1975,180.0,72,24.4
237,238,male,John,Doe,123 Main Street,New York,NY,12345.0,United States,johndoe@email.com1234567890,1/1/1975,180.0,72,24.4
244,245,male,John,Doe,123 Main Street,New York,NY,12345.0,United States,johndoe@email.com1234567890,1/1/1975,180.0,72,24.4
251,252,male,John,Doe,123 Main Street,New York,NY,12345.0,United States,johndoe@email.com1234567890,1/1/1975,180.0,72,24.4
277,278,male,John,Doe,123 Main Street,New York,NY,12345.0,United States,johndoe@email.com1234567890,1/1/1975,180.0,72,24.4

In [32]:
# treatment_table : 


treatments.duplicated().sum()

np.int64(1)

In [34]:

treatments[treatments.duplicated()]

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
136,joseph,day,29u - 36u,-,7.7,7.19,NaN

In [36]:
treatments[treatments.duplicated(subset = ['given_name' , 'surname'])]

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
136,joseph,day,29u - 36u,-,7.7,7.19,NaN

In [37]:
#--> treatments_cut table : 

treatments_cut[treatments_cut.duplicated(subset = ['given_name' , 'surname'])]

Empty DataFrame
Columns: [given_name, surname, auralin, novodra, hba1c_start, hba1c_end, hba1c_change]
Index: []

In [39]:
#--> adverse_reaction Table : 

adverse_reactions.duplicated().sum()

np.int64(0)

In [40]:
#--> checking mathematical summary on the numerical columns using describe : 

patients.describe()

       patient_id      zip_code      weight      height         bmi
count  503.000000    491.000000  503.000000  503.000000  503.000000
mean   252.000000  49084.118126  173.434990   66.634195   27.483897
std    145.347859  30265.807442   33.916741    4.411297    5.276438
min      1.000000   1002.000000   48.800000   27.000000   17.100000
25%    126.500000  21920.500000  149.300000   63.000000   23.300000
50%    252.000000  48057.000000  175.300000   67.000000   27.200000
75%    377.500000  75679.000000  199.500000   70.000000   31.750000
max    503.000000  99701.000000  255.900000   79.000000   37.700000

In [41]:
patients[patients['weight'] == 48.800000]   #--> 48 pound is 21 kg , it is a misplaced error , it can't possible.

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
210,211,female,Camilla,Zaitseva,4689 Briarhill Lane,Wooster,OH,44691.0,United States,330-202-2145CamillaZaitseva@superrito.com,11/26/1938,48.8,63,19.1

In [43]:
patients[patients['height'] == 27 ]    #--> height = 27 inches is quite abnormal , it is also can't possible.

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
4,5,male,Tim,Neudorf,1428 Turkey Pen Lane,Dothan,AL,36303.0,United States,334-515-7487TimNeudorf@cuvox.de,2/18/1928,192.3,27,26.1

In [45]:
treatments.describe()

       hba1c_start   hba1c_end  hba1c_change
count   280.000000  280.000000    171.000000
mean      7.985929    7.589286      0.546023
std       0.568638    0.569672      0.279555
min       7.500000    7.010000      0.200000
25%       7.660000    7.270000      0.340000
50%       7.800000    7.420000      0.380000
75%       7.970000    7.570000      0.920000
max       9.950000    9.580000      0.990000

In [46]:
treatments.sort_values('hba1c_change' , na_position= 'first')

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
0,veronika,jindrová,41u - 48u,-,7.63,7.20,NaN
2,yukitaka,takenaka,-,39u - 36u,7.68,7.25,NaN
8,saber,ménard,-,54u - 54u,8.08,7.70,NaN
9,asia,woźniak,30u - 36u,-,7.76,7.37,NaN
10,joseph,day,29u - 36u,-,7.70,7.19,NaN
...,...,...,...,...,...,...,...
49,jackson,addison,-,42u - 42u,7.99,7.51,0.98
17,gina,cain,-,36u - 36u,7.88,7.40,0.98
138,giovana,rocha,-,23u - 21u,7.87,7.38,0.99
32,laura,ehrlichmann,-,43u - 40u,7.95,7.46,0.99
245,wu,sung,-,47u - 48u,7.61,7.12,0.99