In [8]:
import pandas as pd
import numpy as np

In [9]:
patients = pd.read_csv(r"C:\Users\ANUBHAV\Data_Analytics\DAP\Data_Cleaning\Dataset\patients.csv")
treatments = pd.read_csv(r"C:\Users\ANUBHAV\Data_Analytics\DAP\Data_Cleaning\Dataset\treatments.csv")
adverse_reactions = pd.read_csv(r"C:\Users\ANUBHAV\Data_Analytics\DAP\Data_Cleaning\Dataset\adverse_reactions.csv")
treatments_cut = pd.read_csv(r"C:\Users\ANUBHAV\Data_Analytics\DAP\Data_Cleaning\Dataset\treatments_cut.csv")

In [10]:
# view datasets 

patients.head()

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
0,1,female,Zoe,Wellish,576 Brown Bear Drive,Rancho California,California,92390.0,United States,951-719-9170ZoeWellish@superrito.com,7/10/1976,121.7,66,19.6
1,2,female,Pamela,Hill,2370 University Hill Road,Armstrong,Illinois,61812.0,United States,PamelaSHill@cuvox.de+1 (217) 569-3204,4/3/1967,118.8,66,19.2
2,3,male,Jae,Debord,1493 Poling Farm Road,York,Nebraska,68467.0,United States,402-363-6804JaeMDebord@gustr.com,2/19/1980,177.8,71,24.8
3,4,male,Liêm,Phan,2335 Webster Street,Woodbridge,NJ,7095.0,United States,PhanBaLiem@jourrapide.com+1 (732) 636-8246,7/26/1951,220.9,70,31.7
4,5,male,Tim,Neudorf,1428 Turkey Pen Lane,Dothan,AL,36303.0,United States,334-515-7487TimNeudorf@cuvox.de,2/18/1928,192.3,27,26.1

In [11]:
treatments.head()

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
0,veronika,jindrová,41u - 48u,-,7.63,7.20,NaN
1,elliot,richardson,-,40u - 45u,7.56,7.09,0.97
2,yukitaka,takenaka,-,39u - 36u,7.68,7.25,NaN
3,skye,gormanston,33u - 36u,-,7.97,7.62,0.35
4,alissa,montez,-,33u - 29u,7.78,7.46,0.32

In [12]:
treatments_cut.head()

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
0,jožka,resanovič,22u - 30u,-,7.56,7.22,0.34
1,inunnguaq,heilmann,57u - 67u,-,7.85,7.45,NaN
2,alwin,svensson,36u - 39u,-,7.78,7.34,NaN
3,thể,lương,-,61u - 64u,7.64,7.22,0.92
4,amanda,ribeiro,36u - 44u,-,7.85,7.47,0.38

In [13]:
adverse_reactions.head()

  given_name     surname           adverse_reaction
0      berta  napolitani  injection site discomfort
1       lena        baer               hypoglycemia
2     joseph         day               hypoglycemia
3     flavia  fiorentino                      cough
4    manouck     wubbels          throat irritation

# 1. Summary About the data : 

- This is a dataset about 500 patients of which 350 patients participated in a clinincal trial. None of the patients were using Novodra ( a popular 
injectable insulin ) or Auralin ( the oral insulin being researched ) as their primary source of insulin before. All were experiencing elevated HbA1c levels.
- All 350 patients were treated with Novodra to establish a baseline HbA1c level and insulin dose. After 4 weeks , which isn't enough time to capture all the change in HbA1c that can be attributed by the switch to Auralin or Novodra :

   --> 175 patients switched to Auralin for 24 weeks.
   
   --> 175 patients continued using Novodra for 24 weeks.

# 2. Write Column descriptions : 

- patient_id : the unique identifier for each patient in the Master Patient Index ( i.e. patient database ) of the pharmaceutical company that is
  producing Auralin.
- assigned_sex : the assigned sex of each patient at birth ( male or female ) .
- given_name : the given name ( i.e first name ) of each patient.
- surname : the surname ( i.e last name ) of each patient.
- address : the main address for each patient.
- city : the corrosponding city for the main address of each patient.
- state : the corrosponding state for the main address of each patient.
- zip_code : the corrosponding zip code for the main address of each patient.
- country : the corrosponding country for the main address of each patient ( all United states for this clinical trial ).
- contact : phone number and email information for each patient.
- birthdate : the date of birth of each patient ( month / day / year ). The inclusion criteria for this clinical trial is age >= 18 ( there is no
  maximum age because diabetes is a growing problem among the elderly population.
- weight : the weight of each patient in pounds (lbs).
- height : the height of each patient in inches (in).
- bmi : the Body Mass Index(BMI) of eachh patient. BMI is a simple calculation using a person's height and weight. The formula is BMI = kg/m2 where kg  is a person's weight in kilograms and m2 is their in metres squared. A BMI of 25.0 or more is overweight , while the healthy range is 18.5 to 24.9. The inclusion criteria for this clinical trial is 16 >= BMI >= 38.